export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  EDIT_SELECTED_PRODUCT: "EDIT_SELECTED_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
};

export const ActionTypesOrder = {
  SET_DELIVERED_ORDERS: "SET_DELIVERED_ORDERS",
  SET_NOTDELIVERED_ORDERS: "SET_NOTDELIVERED_ORDERS",
  DELIVERED_ORDER:"DELIVERED_ORDER",
};
